-- ANALYTICS.ORDERS_DAILY - stands in for a compiled dbt mart model.

DEFINE DYNAMIC TABLE DCM_PROMO_DEMO.{{env_name}}_ANALYTICS.ORDERS_DAILY
WAREHOUSE = 'ORDERS_PIPELINE_{{env_name}}_WH'
TARGET_LAG = '1 hour'
INITIALIZE = 'ON_CREATE'
AS
SELECT
    ORDER_DATE,
    COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM DCM_PROMO_DEMO.{{env_name}}_RAW.ORDERS
WHERE STATUS != 'CANCELLED'
GROUP BY ORDER_DATE;
