-- SERVE.ORDERS_SUMMARY - consumption layer view.

DEFINE VIEW DCM_PROMO_DEMO.{{env_name}}_SERVE.ORDERS_SUMMARY
AS
SELECT
    ORDER_DATE,
    ORDER_COUNT,
    TOTAL_REVENUE,
    ROUND(TOTAL_REVENUE / NULLIF(ORDER_COUNT, 0), 2) AS AVG_ORDER_VALUE
FROM DCM_PROMO_DEMO.{{env_name}}_ANALYTICS.ORDERS_DAILY;
